---
- Name: assign values for OSP Image and retrieve image_vars
- get_url:
    url: "{{ image_vars.url }}"
    dest: "{{ image_vars.dest }}"
    #tags: "{{ image_vars.tags }}"
    name: "{{ image_vars.name }}"
- os_image:
    cloud: "{{ osp_cloud_name }}"
    name: "{{ os_image.name }}"
    container_format: "{{ os_image.container_format }}"
    disk_format: "{{ os_image.disk_format }}"
    state: "{{ os_image.state }}"
    filename: "{{ os_image.filename }}"
    #tags: "{{ image_vars.os_image.tags }}"
